const terms = {
  all: [
    'abstaine',
    'abstinence',
    'abuse',
    'alcohol',
    'alcoholic',
    'anstie',
    'anstie’s Limit',
    'beer',
    'cider',
    'cirrhosis of the liver',
    'craving',
    'delirium tremens',
    'dram',
    'drink',
    'drinker',
    'drunkard',
    'excess',
    'grocers',
    'habit',
    'habitual',
    'inebriety',
    'intemperance',
    'intemperate',
    'licensed Victuallers',
    'liquor',
    'liquor trade',
    'liver disease',
    'moderate',
    'moderation',
    'nourishing',
    'port',
    'publican',
    'rum',
    'secret',
    'sherry',
    'temperance',
    'temperate',
    'tippler',
    'toper',
    'whiskey',
    'whisky',
    'wine'
  ],
  critical:  [
    'abstainers',
    'abstinence',
    'abuse',
    'alcoholic',
    'anstie',
    'cirrhosis ',
    'craving',
    'tremens',
    'drunkard',
    'excess',
    'grocers',
    'habit',
    'habitual',
    'inebriety',
    'intemperance',
    'intemperate',
    'victuallers',
    'moderate',
    'moderation',
    'publican',
    'secret',
    'temperance',
    'temperate',
    'tippler',
    'toper'
  ],
  neutral: [
    'alcohol',
    'alcoholic',
    'ale',
    'beer',
    'brandy',
    'cider',
    'dram',
    'drink',
    'drinker',
    'gin',
    'grocers',
    'victuallers',
    'liquor',
    'moderate',
    'moderation',
    'nourishing',
    'port',
    'publican',
    'rum',
    'sherry',
    'temperate',
    'tippler',
    'toper',
    'whiskey',
    'whisky',
    'wine'
  ]
};

module.exports.terms = terms;
